apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: lars-test-patcher
subjects:
- kind: ServiceAccount
  name: patcher
roleRef:
  kind: ClusterRole
  name: lars-test-patcher
  apiGroup: rbac.authorization.k8s.io
