apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: whoami
          image: docker.io/containous/whoami:latest
          imagePullPolicy: IfNotPresent
          args:
            - --port
            - "8080"
