apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lars-test

commonLabels:
  app: patch-test

resources:
- sa.yaml
- cr.yaml
- crb.yaml
- deployment.yaml
- patch.yaml

configurations:
- namespace.yaml
