apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: test-patch
spec:
  serviceAccountRef:
    name: patcher
  patches:
    test-patch:
      targetObjectRef:
        apiVersion: apps/v1
        kind: Deployment
        name: example
      patchType: application/strategic-merge-patch+json
      patchTemplate: |
        metadata:
          labels:
            "test-label": "some-randon-value"
